apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: pyspark-pi
  namespace: spark
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "datamechanics/spark:3.2-latest"
  imagePullPolicy: Always
  mainApplicationFile: local:///opt/spark/examples/src/main/python/pi.py
  sparkVersion: 3.2.1"
  sparkConf:
    "spark.eventLog.enabled": "true"
    "spark.eventLog.dir": "s3a://<spark-events-logs-bucket>/logs/"
    "spark.hadoop.fs.s3a.aws.credentials.provider": "com.amazonaws.auth.WebIdentityTokenCredentialsProvider"
  sparkUIOptions:
    ingressAnnotations:
      cert-manager.io/cluster-issuer: cert-issuer
      kubernetes.io/ingress.class: nginx
    ingressTLS:
      - secretName: pyspark-pi-tls
        hosts:
          - pyspark-pi.<rout53_domain>
  restartPolicy:
    type: Never
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    nodeSelector:
      eks.amazonaws.com/nodegroup: spot_group
    labels:
      version: 3.2.1
    serviceAccount: spark-operator-spark
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    nodeSelector:
      eks.amazonaws.com/nodegroup: spot_group
    labels:
      version: 3.2.1